name: ClopePlugin
version: 1.0.0
main: io.papermc.clope.ClopePlugin
description: An example plugin
author: PaperMC
website: https://papermc.io
api-version: '1.20'
commands:
  clope:
    description: Donne une cigarette
    usage: /clope
